In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

x = torch.randn(4, 2)
y = torch.randn(4, 1)

model = nn.Linear(2, 1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

optimizer.zero_grad()
pred = model(x)
loss = loss_fn(pred, y)
loss.backward()
optimizer.step()

print(f"loss: {loss.item()}")

loss: 0.6994926333427429


In [ ]:
import torch

w = torch.tensor(2.0, requires_grad=True)

loss1 = w ** 2
loss1.backward() # expected: 4
print(f"w grad: {w.grad}") # w grad: 4.0

loss2 = w ** 2
loss2.backward() # expected: 4
print(f"w grad: {w.grad}") # w grad: 8.0

w grad: 4.0
w grad: 8.0


In [6]:
import torch
import torch.nn as nn
import torch.optim as otpim

x = torch.randn(4, 2)
y = torch.rand(4, 1)

model = nn.Linear(2, 1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

pred = model(x)
loss = loss_fn(pred, y)

print(f"before backward: {model.weight.grad}, {model.bias.grad}")
loss.backward()

print(f"before zero_grad: {model.weight.grad}, {model.bias.grad}")

# set_to_none (bool, optional): Instead of setting to zero, set the grads to None. Default: ``True``
optimizer.zero_grad(set_to_none=False)

print(f"after zero_grad: {model.weight.grad}, {model.bias.grad}")

optimizer.zero_grad(set_to_none=True)

print(f"after zero_grad: {model.weight.grad}, {model.bias.grad}")

before backward: None, None
before zero_grad: tensor([[-0.4176, -1.9823]]), tensor([-2.3780])
after zero_grad: tensor([[0., 0.]]), tensor([0.])
after zero_grad: None, None


In [12]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)

x = torch.randn(4, 2)
y = torch.randn(4, 1)

model = nn.Linear(2, 1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# print(model.weight)
weight_before = model.weight.detach().clone()
# print(weight_before)

optimizer.zero_grad()
pred = model(x)
loss = loss_fn(pred, y)
loss.backward()
optimizer.step()

# print(model.weight)
weight_after = model.weight.detach().clone()
# print(weight_after)

print(f"weight before: {weight_before}")
print(f"weight after: {weight_after}")
print(f"changed: {not torch.allclose(weight_before, weight_after)}")

weight before: tensor([[-0.5582, -0.3260]])
weight after: tensor([[-0.5337, -0.3312]])
changed: True


In [20]:
def check_one_step_update(model, optimizer, loss_fn, x, y):
    first_param_before = next(model.parameters()).detach().clone()

    optimizer.zero_grad()
    pred = model(x)
    loss = loss_fn(pred, y)
    loss.backward()
    optimizer.step()

    first_param_after = next(model.parameters()).detach().clone()

    print(f"loss: {loss.item()}")
    print(f"parameter changed: {not torch.allclose(first_param_before, first_param_after)}")

check_one_step_update(model, optimizer, loss_fn, x, y)

loss: 1.25216543674469
parameter changed: True


In [24]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)

x = torch.randn(8, 3)
y = torch.randn(8, 1)

model = nn.Linear(3, 1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.05)

for step in range(3):
    #TODO 1. gradient 초기화
    optimizer.zero_grad()

    #TODO 2. forward
    pred = model(x)

    #TODO 3. loss 계산
    loss = loss_fn(pred, y)

    #TODO 4. backward
    loss.backward()
    for name, param in model.named_parameters():
        print(f"name: {name}\nparameters: {param}\n")

    #TODO 5. parameter update
    optimizer.step()

    #TODO 6. loss 출력
    print(f"step: {step}, loss: {loss.item()}\n")

name: weight
parameters: Parameter containing:
tensor([[ 0.1826, -0.0100,  0.4518]], requires_grad=True)

name: bias
parameters: Parameter containing:
tensor([-0.4102], requires_grad=True)

step: 0, loss: 1.5056692361831665

name: weight
parameters: Parameter containing:
tensor([[0.1246, 0.0117, 0.3678]], requires_grad=True)

name: bias
parameters: Parameter containing:
tensor([-0.3116], requires_grad=True)

step: 1, loss: 1.129276156425476

name: weight
parameters: Parameter containing:
tensor([[0.0823, 0.0343, 0.3006]], requires_grad=True)

name: bias
parameters: Parameter containing:
tensor([-0.2263], requires_grad=True)

step: 2, loss: 0.8711472153663635

