In [1]:
import torch
from torch.utils.data import TensorDataset, DataLoader

X = torch.randn(20, 4)
y = torch.tensor([0, 1] * 10, dtype=torch.long)

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

X shape: torch.Size([20, 4])
y shape: torch.Size([20])


In [ ]:
# Dataset wrapping tensors.
# Each sample will be retrieved by indexing tensors along the first dimension.
dataset = TensorDataset(X, y)

print(f"dataset length: {len(dataset)}")

sample_x, sample_y = dataset[0]

print(f"sample_x shape: {sample_x.shape}")
print(f"sample_y: {sample_y.shape}")

dataset length: 20
sample_x shape: torch.Size([4])
sample_y: torch.Size([])


In [4]:
loader = DataLoader(
    dataset,
    batch_size=5,
    shuffle=True
)

batch_x, batch_y = next(iter(loader))

print(f"batch_x shape: {batch_x.shape}")
print(f"batch_y shape: {batch_y.shape}")
print(f"batch_y: {batch_y}")

batch_x shape: torch.Size([5, 4])
batch_y shape: torch.Size([5])
batch_y: tensor([0, 1, 1, 0, 1])


In [5]:
import torch.nn as nn
import torch.optim as optim

model = nn.Linear(4, 2)
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

for batch_x, batch_y in loader:
    optimizer.zero_grad()
    logits = model(batch_x)
    loss = loss_fn(logits, batch_y)
    loss.backward()
    print(f"after backward grad: {model.weight.grad}")
    optimizer.step()
    print(f"after otpimizer.step: {model.weight}")
    print(f"loss: {loss.item()}\n")



after backward grad: tensor([[ 0.0296, -0.0662, -0.0670,  0.5352],
        [-0.0296,  0.0662,  0.0670, -0.5352]])
after otpimizer.step: Parameter containing:
tensor([[ 0.0067,  0.4221, -0.2706,  0.3842],
        [ 0.0528,  0.2463,  0.0995, -0.0245]], requires_grad=True)
loss: 0.8358938097953796

after backward grad: tensor([[ 0.0531, -0.0465, -0.1868, -0.0653],
        [-0.0531,  0.0465,  0.1868,  0.0653]])
after otpimizer.step: Parameter containing:
tensor([[ 0.0057,  0.4231, -0.2697,  0.3836],
        [ 0.0538,  0.2453,  0.0986, -0.0239]], requires_grad=True)
loss: 0.8047689199447632

after backward grad: tensor([[-0.1259, -0.1226,  0.2801,  0.4178],
        [ 0.1259,  0.1226, -0.2801, -0.4178]])
after otpimizer.step: Parameter containing:
tensor([[ 0.0060,  0.4241, -0.2698,  0.3829],
        [ 0.0536,  0.2444,  0.0987, -0.0232]], requires_grad=True)
loss: 0.7002120018005371

after backward grad: tensor([[-0.1578,  0.5308, -0.2454,  0.1262],
        [ 0.1578, -0.5308,  0.2454, -0.126

In [8]:
X = torch.randn(20, 4)
y_wrong = torch.tensor([0, 1] * 9, dtype=torch.long)

try:
    dataset_wrong = TensorDataset(X, y_wrong)
except AssertionError as e:
    print(e)    # Size mismatch between tensors
# except RuntimeError as e:
#     print(e)

Size mismatch between tensors


In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# 1. 샘플 수는 100개입니다.
# 2. feature 수는 6개입니다.
# 3. class는 3개입니다.
# 4. batch size는 16입니다.
# 5. 첫 번째 batch의 shape를 출력하세요.

X = torch.randn(100, 6)
# (function) def randint(
#     low: int,
#     high: int,
#     size: _size,
#     *,
#     generator: Generator | None = None,
#     dtype: dtype | None = None,
#     device: DeviceLikeType | None = None,
#     requires_grad: bool = False,
#     pin_memory: bool = False
# ) -> Tensor
y = torch.randint(low=0, high=3, size=(100,), dtype=torch.long)

dataset = TensorDataset(X, y)
loader = DataLoader(
    # dataset: Dataset[Unknown],
    dataset = dataset,
    # batch_size: int | None = 1,
    batch_size = 16,
    # shuffle: bool | None = None,
    shuffle = True,
    # sampler: Sampler[Unknown] | Iterable[Unknown] | None = None,
    # batch_sampler: Sampler[list[Unknown]] | Iterable[list[Unknown]] | None = None,
    # num_workers: int = 0,
    # collate_fn: _collate_fn_t[Unknown] | None = None,
    # pin_memory: bool = False,
    # drop_last: bool = False,
    # timeout: float = 0,
    # worker_init_fn: _worker_init_fn_t | None = None,
    # multiprocessing_context: Unknown | None = None,
    # generator: Unknown | None = None,
    # *,
    # prefetch_factor: int | None = None,
    # persistent_workers: bool = False,
    # pin_memory_device: str = "",
    # in_order: bool = True
)

batch_x, batch_y = next(iter(loader))

print(f"batch_x shape: {batch_x.shape}")
print(f"batch_y shape: {batch_y.shape}")
print(f"batch_y dtype: {batch_y.dtype}")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1520197154.py, line 28)