In [2]:
import random
import numpy as np
import torch

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

In [3]:
set_seed(42)
x1 = torch.randn(3)

set_seed(42)
x2 = torch.randn(3)

print(x1)
print(x2)

tensor([0.3367, 0.1288, 0.2345])
tensor([0.3367, 0.1288, 0.2345])


In [5]:
from torch.utils.data import TensorDataset, DataLoader, random_split

set_seed(42)

X = torch.randn(100, 4)
y = torch.randint(0, 3, size=(100,))
dataset = TensorDataset(X, y)

split_generator = torch.Generator().manual_seed(42)
train_dataset, val_dataset = random_split(dataset, [80,20], generator=split_generator)

loader_generator = torch.Generator().manual_seed(42)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, generator=loader_generator)

first_batch_x, first_batch_y = next(iter(train_loader))
print(first_batch_x.shape, first_batch_y.shape)

torch.Size([16, 4]) torch.Size([16])


In [ ]:
# 다음 조건을 만족하는 `set_seed` 함수를 작성하세요.

# 1. Python random seed를 고정합니다.
# 2. NumPy random seed를 고정합니다.
# 3. PyTorch CPU random seed를 고정합니다.
# 4. CUDA가 사용 가능하면 CUDA seed도 고정합니다.

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

set_seed(19950301)
print(torch.randn(3))
print(torch.randn(3))

set_seed(19950301)
print(torch.randn(3))
print(torch.randn(3))

tensor([-0.5309, -0.8593,  1.9269])
tensor([ 0.7700,  0.8168, -0.6806])
tensor([-0.5309, -0.8593,  1.9269])
tensor([ 0.7700,  0.8168, -0.6806])
